apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        imagePullPolicy: Never # Never when using local image
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "512m"
          limits:
            memory: "1024Mi"
            cpu: "512m"
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/mydb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_REDIS_HOST
          value: redis://redis:6379
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: REDISSON_ADDRESS
          value: redis://redis:6379
        - name: REDISSON_PASSWORD
          value: redis
