spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #format_sql: true
    hibernate:
      ddl-auto: create-drop # update
    # show-sql: true
  redis:
    host: localhost
    port: 6379
redisson:
    address: redis://localhost:6379
    password: redis
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-detail: always